import * as React from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { X } from 'lucide-react';
import { cn } from '@/lib/utils';
export const Sheet = DialogPrimitive.Root;
export const SheetTrigger = DialogPrimitive.Trigger;
export const SheetClose = DialogPrimitive.Close;
export const SheetPortal = DialogPrimitive.Portal;
export const SheetContent = React.forwardRef<React.ElementRef<typeof DialogPrimitive.Content>, React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content> & { side?: 'left' | 'right' }>(({ className, children, side = 'left', ...props }, ref) => <SheetPortal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/80" /><DialogPrimitive.Content ref={ref} className={cn('fixed inset-y-0 z-50 flex w-72 flex-col gap-4 border bg-background p-6 shadow-lg', side === 'left' ? 'left-0' : 'right-0', className)} {...props}>{children}<DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 hover:opacity-100"><X className="size-4" /><span className="sr-only">Đóng</span></DialogPrimitive.Close></DialogPrimitive.Content></SheetPortal>);
SheetContent.displayName = 'SheetContent';
